### PR TITLE
DLS-9976: [OGD Stubs] Improve Session/request ID Logging

### PR DESCRIPTION
**Pull request by johno1985**

### CODE REVIEW

**Comment by johno1985** [comment]
rebuild

**Comment by johno1985** [comment]
just spotted some static years defined in the messages_en.txt file. Do those need addressing also?

**Comment by johno1985** [comment]
rebuild

**Comment by johno1985** [comment]
rebuild

**Review by TomRafferty — CHANGES_REQUESTED** [review]
I get some warnings on this locally, but other than that all looks good 😃

**Comment by johno1985** [comment]
> I get some warnings on this locally, but other than that all looks good 😃

Do you want me to address the warnings or are you happy to approve?

**Review by TomRafferty — APPROVED** [review]

**Pull request merged**
